sonar.sources=litex
sonar.tests=test
sonar.test.inclusions=test/**/test_*.py

sonar.python.version=3.9,3.10,3.11,3.12,3.13
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/__pycache__/**,**/build/**,**/dist/**,litex/build/sim/core/modules/**
